# Generated by Django 4.2.7 on 2026-04-03 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('krushiApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agriloan',
            name='category',
            field=models.CharField(choices=[('Credit Cards', 'Credit Cards'), ('Crop Loans', 'Crop Loans'), ('Equipment Loans', 'Equipment Loans')], default='Crop Loans', max_length=100),
        ),
        migrations.AddField(
            model_name='agriloan',
            name='duration',
            field=models.CharField(blank=True, help_text='e.g., 12 months, 5-7 years', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='governmentscheme',
            name='benefits',
            field=models.TextField(blank=True, help_text='Detailed benefits offered to farmers.', null=True),
        ),
        migrations.AddField(
            model_name='governmentscheme',
            name='eligibility',
            field=models.TextField(blank=True, help_text='Who is eligible for this scheme?', null=True),
        ),
        migrations.AddField(
            model_name='msprate',
            name='percentage_increase',
            field=models.CharField(blank=True, help_text='Percentage increase compared to last year (e.g., 7%)', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='msprate',
            name='year',
            field=models.CharField(default='2024-25', help_text='Target financial year (e.g., 2024-25)', max_length=20),
        ),
        migrations.AlterField(
            model_name='agriloan',
            name='details',
            field=models.TextField(blank=True, help_text='List of required documents and terms.', null=True),
        ),
        migrations.AlterField(
            model_name='governmentscheme',
            name='description',
            field=models.TextField(blank=True, help_text='A brief overview of the scheme.', null=True),
        ),
        migrations.AlterField(
            model_name='msprate',
            name='rate',
            field=models.DecimalField(decimal_places=2, help_text='Rate in ₹ per Quintal', max_digits=10),
        ),
        migrations.AlterField(
            model_name='msprate',
            name='season',
            field=models.CharField(choices=[('Kharif', 'Kharif'), ('Rabi', 'Rabi')], max_length=100),
        ),
    ]
