# Generated by Django 6.0.2 on 2026-03-20 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('krushiApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agriloan',
            name='details_hi',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='agriloan',
            name='details_mr',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='agriloan',
            name='name_hi',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='agriloan',
            name='name_mr',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='agriloan',
            name='summary_hi',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='agriloan',
            name='summary_mr',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='msp',
            name='crop_name_hi',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='msp',
            name='crop_name_mr',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='scheme',
            name='benefits_hi',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='scheme',
            name='benefits_mr',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='scheme',
            name='description_hi',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='scheme',
            name='description_mr',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='scheme',
            name='eligibility_hi',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='scheme',
            name='eligibility_mr',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='scheme',
            name='title_hi',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='scheme',
            name='title_mr',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
