# Generated by Django 4.2.7 on 2026-04-03 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('krushiApp', '0002_agriloan_category_agriloan_duration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agriloan',
            name='apply_url',
            field=models.URLField(blank=True, help_text='Link to the official bank application portal.', null=True),
        ),
        migrations.AddField(
            model_name='governmentscheme',
            name='apply_url',
            field=models.URLField(blank=True, help_text='Link to the official government application portal.', null=True),
        ),
    ]
