# Generated by Django 4.2.7 on 2026-04-03 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('krushiApp', '0004_notification_farmerprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farmerprofile',
            name='user',
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
        migrations.DeleteModel(
            name='FarmerProfile',
        ),
    ]
